### ISSUE TITLE
data, domain 모듈 만들기

### ISSUE THREAD

**Issue by BeokBeok** [2giwon/UnsplashAndroid#1]
# 요구사항
- 순수 코틀린 모듈인 domain 모듈을 만든다.
- 순수 코틀린 모듈인 data 모듈을 만든다.
- data 모듈은 domain 모듈을 implementation 해야 한다.
- app 모듈은 data, domain 모듈을 implementation 해야 한다.

**Comment by 2giwon** [comment]
cee54f02daf2c23022b67fdac3b674c146244101
945a4d6a9242918779f53d0cab67ded058d8aea1
24ca503bb992564a577d2b3743103a1139e577e0
aeb7c232c9c87d6ec38ebe9fe18c24326114cc75 적용 했습니다.
