### ISSUE TITLE
HTTP 연동

### ISSUE THREAD

**Issue by BeokBeok** [2giwon/UnsplashAndroid#4]
#### Unsplash 사진을 랜덤으로 가져올 수 있어야 합니다.
- GET, https://api.unsplash.com/photos/random
- urls 의 small 필드만 사용합니다.

---

### 프로그래밍 요구사항
1. Unsplash 사진을 랜덤으로 가져오는 기능은 data 모듈에 구현되어야 합니다.
1. data 모듈의 구현체는 모두 internal 키워드가 붙어야합니다.

**Comment by 2giwon** [comment]
https://unsplash.com/oauth/applications/257956
